### ISSUE TITLE
Files may be missing from ZIP download

### ISSUE THREAD

**Issue by rdogmartin** [rdogmartin/GalleryServer#1]
Files that don't have a web-optimized version are not included in the ZIP download that is created when multiple items are selected and the download command is invoked. This includes documents such as text files and small images.

What should happen: GS should substitute the original media file when the web-optimized one doesn't exist.

**Comment by rdogmartin** [comment]
Modified function so that original file is used when the web-optimized one doesn't exist.

**Comment by Jogai** [comment]
What do you think of moving to bundling with webpack, parcel or any of the now popular systems to produce a bundle?

**Comment by rdogmartin** [comment]
Webpack is a module bundler. This thread is talking about a user downloading multiple media files from their gallery. For this, a ZIP file is the best approach.
